export const maintenanceItems = [
        {
            "station" : "Main Building",
            "item" : "Building (2609 Seiferth)",
            "tasks" : ["Clean Kitchen","Replace HVAC Filters","Clean Front Room","Clean Bathroom","Sweep Production Floor","Wipe Production Tables","Dust Product Sample Shelves","Plumbing Problem","Electrical Problem","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Warehouses",
            "item" : "Building (2606 Seiferth)",
            "tasks" : ["Plumbing Problem", "Electrical Problem", "Replace HVAC Filter", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Warehouses",
            "item" : "Building (2617 Seiferth)",
            "tasks" : ["Plumbing Problem", "Electrical Problem", "Replace HVAC Filter", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Konica Printers",
            "item" : "Printer (Konica C6085)",
            "tasks" : ["Cleaned toner drum Cyan", "Cleaned toner drum Magenta", "Cleaned toner drum Yellow", "Cleaned toner drum Black", "Cleaned Glass", "Excessive Jamming", "Fiery Issue", "Error Message", "Image Alignment Issue", "Print Quality Issue", "Replace Staples", "Replace Cyan Ink","Replace Magenta Ink","Replace Yellow Ink","Replace Black Ink","Replace Waste Toner Container","Replaced Fuser", "Service Call Placed", "Service Call Resolved", "Service Call Update", "Submit Click Meter Reading", "Will Not Print PDF","Perform Auto Color Calibration","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Konica Printers",
            "item" : "Printer (Konica C6085) B",
            "tasks" : ["Cleaned toner drum Cyan", "Cleaned toner drum Magenta", "Cleaned toner drum Yellow", "Cleaned toner drum Black", "Cleaned Glass", "Excessive Jamming", "Fiery Issue", "Error Message", "Image Alignment Issue", "Print Quality Issue", "Replace Staples", "Replace Cyan Ink","Replace Magenta Ink","Replace Yellow Ink","Replace Black Ink","Replace Waste Toner Container","Replaced Fuser", "Service Call Placed", "Service Call Resolved", "Service Call Update", "Submit Click Meter Reading", "Will Not Print PDF","Perform Auto Color Calibration","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Brother Printers",
            "item" : "Printer (Brother HL-L9410CDN) A",
            "tasks" : [ "Replace Cyan Toner", "Replace Magenta Toner", "Replace Yellow Toner", "Replace Black Toner", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Brother Printers",
            "item" : "Printer (Brother HL-8360CDW) B",
            "tasks" : [ "Replace Cyan Toner", "Replace Magenta Toner", "Replace Yellow Toner", "Replace Black Toner", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Mimaki Printers",
            "item" : "Printer (Mimaki) A",
            "tasks" : [ "Replace Cyan Ink", "Replace Magenta Ink", "Replace Yellow Ink", "Replace Black Ink", "Replace White Ink", "Replace Clear Ink", "Head Strike", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Mimaki Printers",
            "item" : "Printer (Mimaki) B",
            "tasks" : [ "Replace Cyan Ink", "Replace Magenta Ink", "Replace Yellow Ink", "Replace Black Ink", "Replace White Ink", "Replace Clear Toner", "Head Strike", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Mimaki Printers",
            "item" : "Printer (Mimaki) C",
            "tasks" : [ "Replace Cyan Ink", "Replace Magenta Ink", "Replace Yellow Ink", "Replace Black Ink", "Replace White Ink", "Replace Clear Ink", "Head Strike", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Mimaki Printers",
            "item" : "Printer (Mimaki) D",
            "tasks" : [ "Replace Cyan Ink", "Replace Magenta Ink", "Replace Yellow Ink", "Replace Black Ink", "Replace White Ink", "Replace Clear Toner", "Head Strike", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Die Cutters",
            "item" : "RDC A",
            "tasks" : ["Calibrate registration sensor", "Recipe adjustment", "Replace die", "Order parts", "Stripper adjustment/repair", "Clean and Lubricate", "Air Feeder Adjustment", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Die Cutters",
            "item" : "RDC B",
            "tasks" : ["Calibrate registration sensor", "Recipe adjustment", "Replace die", "Order parts", "Stripper adjustment/repair", "Clean and Lubricate", "Air Feeder Adjustment", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Die Cutters",
            "item" : "PETE Poker Die Cutter",
            "tasks" : ["Lubrication", "Replace Foam, see notes", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Clamshell Cutters",
            "item" : "Clamshell Cutter (Crest 2026)",
            "tasks" : ["Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "SCCs",
            "item" : "SCC A",
            "tasks" : ["Empty Waste Container", "Lubricate",  "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Texturizers",
            "item" : "Texturizer A (Yiwu Innovo YW650G)",
            "tasks" : ["Cleaning", "Lubricate",  "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Texturizers",
            "item" : "Texturizer B (Yiwu Innovo YW650G)",
            "tasks" : ["Cleaning", "Lubricate",  "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Vacuum Former",
            "item" : "Vacuum Former (Formech NewForm)",
            "tasks" : ["Cleaning", "Replace Seal",  "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "UV Coater Stackers",
            "item" : "UV Coater Stacker (Teclighting TRUVF-16D)",
            "tasks" : ["Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "UV Coater Flip Stations",
            "item" : "UV Coater Flip Station (Teclighting TRUVF-16D FLP)",
            "tasks" : ["Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "UV Coaters",
            "item" : "UV Coater A (Teclighting TRUVF-16D)",
            "tasks" : ["Change Doctor Blade","Change UV Lamp","Change IR Lamp","Change Rubber Roller","Change Hose","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "UV Coaters",
            "item" : "UV Coater B (Teclighting TRUVF-16D)",
            "tasks" : ["Change Doctor Blade","Change UV Lamp","Change IR Lamp","Change Rubber Roller","Change Hose","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Sleekers",
            "item" : "Sleeker (Duplo DFL-500)",
            "tasks" : ["Cleaning", "Lubricate", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Plotters",
            "item" : "Plotter A (JWEI)",
            "tasks" : ["Blade maintenance required","Clean and Lubricate","Cut File Attention required","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Plotters",
            "item" : "Plotter B (JWEI)",
            "tasks" : ["Blade maintenance required","Clean and Lubricate","Cut File Attention required","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Plotters",
            "item" : "Cutting Plotter A (Graphtec FC2250)",
            "tasks" : ["Crazy Cut","Clean Blade","Clean Suction Holes","Replace Blade","Replace Table Surface","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Plotters",
            "item" : "Cutting Plotter B (Graphtec FC2250)",
            "tasks" : ["Crazy Cut","Clean Blade","Clean Suction Holes","Replace Blade","Replace Table Surface","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Laser Cutters",
            "item" : "Laser Cutter A (Trotec Speedy 300)",
            "tasks" : ["Align Mirrors","Clean Lens","Clean Mirrors","Clean Suction Holes","Replace Lens","Replace Mirror","Replace Honeycomb","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Laser Cutters",
            "item" : "Laser Cutter B (Trotec Speedy 300)",
            "tasks" : ["Align Mirrors","Clean Lens","Clean Mirrors","Clean Suction Holes","Replace Lens","Replace Mirror","Replace Honeycomb","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Big Laser Farm",
            "item" : "Laser Cutter Alpha (CAMFive CMA5136T)",
            "tasks" : ["Align Mirrors","Clean Lens","Clean Mirrors","Clean Debris Tray","Replace Lens","Replace Mirror","Replace Honeycomb","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Big Laser Farm",
            "item" : "Laser Cutter Beta (CAMFive CMA5136T)",
            "tasks" : ["Align Mirrors","Clean Lens","Clean Mirrors","Clean Debris Tray","Replace Lens","Replace Mirror","Replace Honeycomb","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Coil Binders",
            "item" : "Coil Binder (Tamerica Officepro-46ei)",
            "tasks" : ["Empty Debris Tray","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Perfect Binders",
            "item" : "Perfect Binder (Sterling Digibinder)",
            "tasks" : ["Compressor","Clean/Replace Glue","Clean Linear Shafts","Lubricate","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Box Machines",
            "item" : "Box Machine, (Yiwu Innovo Co)",
            "tasks" : ["Check state of rubber pressing paddles and brushes.","Wipe all surfaces down with a dampened white rag.","Charge dedicated Box Machine Screwdriver.","Inspect Box Molds and blades.","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Guillotines",
            "item" : "Guillotine Cutter (Triumph 5222 Digicut)",
            "tasks" : ["Replace Blade","Rotate Cutting Stick","Replace Cutting Stick","Replace Fuse","Lubricate","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Parts Counters",
            "item" : "Parts Counter (Dession DS 320LS)",
            "tasks" : ["Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Heat Tunnels",
            "item" : "L Bar/Heat Tunnel (TMC Pro 58/44 Semi-Automatic L Sealer)",
            "tasks" : ["Clean Sealing Wire and Teflon","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Sealers",
            "item" : "I-Bar Sealer (U-Line Tabletop Impulse Sealer)",
            "tasks" : ["Replace Teflon Pad","Replace Heating Element","Replace Fuse","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Air Compressors",
            "item" : "Air Compressor (Mattei ERC 507)",
            "tasks" : ["Reset Onboard Breaker", "Drain Lines", "Drain Tank", "Change Oil","Replace Fuse","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Fork Lifts",
            "item" : "Forklift (Nissan MCP1F2A25LV)",
            "tasks" : ["Check Coolant", "Blow Out Radiator Grill", "Check Oil", "Refill Backup Alarm Fluid" , "Replenish LP Tank" , "Needs Mechanic" , "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Paper Folders",
            "item" : "Paper Folder (Techko LF293)",
            "tasks" : ["Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Kraft Tape Dispensers",
            "item" : "Kraft Tape Dispenser A (Uline H-1036)",
            "tasks" : ["Wash Brush", "Needs technician", "Other: See notes"],
            "status" : "In Use",
        },
        {
            "station" : "Kraft Tape Dispensers",
            "item" : "Kraft Tape Dispenser B (Uline H-1036)",
            "tasks" : ["Wash Brush", "Needs technician", "Other: See notes"],
            "status" : "In Use",
        },
        {
            "station" : "Tape Dispensers",
            "item" : "Tape Dispenser A (SMART ZCM1000)",
            "tasks" : ["Replace Silicone Wheels", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Tape Dispensers",
            "item" : "Tape Dispenser B (SMART ZCM1000)",
            "tasks" : ["Replace Silicone Wheels", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Grommet Punches",
            "item" : "Grommet Punch",
            "tasks" : ["Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Printing Computers",
            "item" : "Printing Computer, Ricoh 901 (iMac)",
            "tasks" : ["Network Problem", "Dropbox Sync Problem", "Update System Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Big Laser Computers",
            "item" : "Laser Computer Alpha (Dell All-in-One)",
            "tasks" : ["Update Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Big Laser Computers",
            "item" : "Laser Computer Beta (HP All-in-One)",
            "tasks" : ["Update Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Old printing computers",
            "item" : "Printing Computer, Konica C6085 (iMac)",
            "tasks" : ["Update Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Old printing computers",
            "item" : "Printing Computer Rico 9100 (iMac)",
            "tasks" : ["Update Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Old printing computers",
            "item" : "Printing Computer Mimaki (iMac/Windows)",
            "tasks" : ["Update Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "JobControl Laser Computer",
            "item" : "Laser Computer A (iMac/Windows)",
            "tasks" : ["Network Problem","JobControl Software Problem", "Update System Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "JobControl Laser Computer",
            "item" : "Laser Computer B (iMac/Windows)",
            "tasks" : ["Network Problem","JobControl Software Problem", "Update System Software","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Zebra Printers",
            "item" : "Zebra Printer A (Zebra ZD410)",
            "tasks" : ["Clean and Lubricate","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Zebra Printers",
            "item" : "Zebra Printer B (Zebra ZD410)",
            "tasks" : ["Clean and Lubricate","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Banders",
            "item" : "Bander A (GB-208 Intelligent Banding Machine)",
            "tasks" : ["Clean Hot Sealer","Clean Dust and Debris","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Banders",
            "item" : "Bander B (GB-208 Intelligent Banding Machine)",
            "tasks" : ["Clean Hot Sealer","Clean Dust and Debris","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Banders",
            "item" : "Bander C (GB-208 Intelligent Banding Machine)",
            "tasks" : ["Clean Hot Sealer","Clean Dust and Debris","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Old shipping computers PC",
            "item" : "Shipping Computer (PC)",
            "tasks" : ["Network Problem", "Email Problem", "Update System Software", "Update Endicia","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Old shipping computers HP",
            "item" : "Shipping Printer (HP 400)",
            "tasks" : ["Network Problem", "Replace Toner", "Ugly Prints", "Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Old shipping computers iMac",
            "item" : "Shipping Computer (iMac)",
            "tasks" : ["Network Problem", "Email Problem", "Update System Software", "Update Endicia","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Water Softener",
            "item" : "Water Softener (Addie CM1-948-32)",
            "tasks" : ["Replenish Salt", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "General",
            "item" : "Other",
            "tasks" : ["See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Old HP printers",
            "item" : "Printer (HP 452dn) A",
            "tasks" : [ "Replace Cyan Toner", "Replace Magenta Toner", "Replace Yellow Toner", "Replace Black Toner", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Old HP printers",
            "item" : "Printer (HP 452dn) B",
            "tasks" : [ "Replace Cyan Toner", "Replace Magenta Toner", "Replace Yellow Toner", "Replace Black Toner", "Needs Technician", "Other: See Notes" ],
            "status" : "In Use",
        },
        {
            "station" : "Old Texturizers",
            "item" : "Texturizer A",
            "tasks" : ["Clean Rollers", "Change Rubber Roller", "Change Texture Roller", "Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Old Texturizers",
            "item" : "Texturizer B",
            "tasks" : ["Clean Rollers", "Change Rubber Roller", "Change Texture Roller", "Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "JWEI Plotter Computer",
            "item" : "JWEI Plotter Computer A",
            "tasks" : ["Software Issue","Connectivity Issue","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "JWEI Plotter Computer",
            "item" : "JWEI Plotter Computer B",
            "tasks" : ["Software Issue","Connectivity Issue","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Plotter Computer",
            "item" : "Plotter Computer B",
            "tasks" : ["Software Issue","Connectivity Issue","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Plotter Computer",
            "item" : "Plotter Computer A (iMac)",
            "tasks" : ["Network Problem","Plotter Software Problem", "Update System Software","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Plotter Computer",
            "item" : "Plotter Computer B (iMac)",
            "tasks" : ["Network Problem","Plotter Software Problem", "Update System Software","Needs Technician","Other: See Notes"],
            "status" : "Retired",
        },
        {
            "station" : "Brother Printers",
            "item" : "Printer (Brother HL-8360CDW) A",
            "tasks" : [ "Replace Cyan Toner", "Replace Magenta Toner", "Replace Yellow Toner", "Replace Black Toner", "Needs Technician", "Other: See Notes" ],
            "status" : "Retired",
        },
        {
            "station" : "Husky Air Compressor",
            "item" : "Air Compressor (Husky C602H)",
            "tasks" : ["Reset Onboard Breaker", "Drain Lines", "Drain Tank", "Change Oil","Replace Fuse","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "Guillotines",
            "item" : "Guillotine Cutter (Triumph 6550-95)",
            "tasks" : ["Replace Blade","Rotate Cutting Stick","Replace Cutting Stick","Replace Fuse","Lubricate","Needs Technician","Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Black-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Black-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Blue-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Blue-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Green-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Green-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Orange-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Orange-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Purple-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Purple-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Red-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Red-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer White-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer White-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Yellow-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Yellow-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Grey-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Silver-003",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Gold-003",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Bronze-003",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Silver-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Gold-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Bronze-002",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Gold-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Silver-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
        {
            "station" : "3D Print Farm",
            "item" : "3d Printer Bronze-001",
            "tasks" : ["Replace Filament", "Replace Nozzle", "Clear Clog", "Print Not Sticking", "Needs Technician", "Other: See Notes"],
            "status" : "In Use",
        },
    ];
