import { baseSchemaProps, dbString, zodString, dbEnum, dbBoolean, dbMediumText, zodMediumText, dbText, zodText, dbRelation, dbDateTime, dbTimestamp, dbInt, dbJson, zodNumber, zodJsonObject } from '../helpers.mjs';

export const hardwareScheduleSchema = {
    kind: 'HardwareSchedule',
    tableName: 'hardwareschedules',
    owner: ['admin', 'maintenanceManager'],
    props: [
        ...baseSchemaProps,
        {
            type: "enum",
            name: "recurrence",
            required: true,
            default: 'monthly',
            db: (prop) => dbEnum(prop),
            enums: ['yearly', 'monthly', 'weekly', 'daily'],
            enumLabels: ['Yearly', 'Monthly', 'Weekly', 'Daily'],
            view: ['owner',],
            edit: ['owner'],
        },
        {
            type: "int",
            name: 'months',
            required: false,
            default: 0,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(12),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "int",
            name: 'weeks',
            required: false,
            default: 0,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(5),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "int",
            name: 'days',
            default: 0,
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(31),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'hardwareItemId',
            required: true,
            filterQualifier: true,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'item',
                kind: 'HardwareItem',
            },
            default: undefined,
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'hardwareTaskId',
            required: true,
            filterQualifier: true,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'task',
                kind: 'HardwareTask',
            },
            default: undefined,
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "string",
            name: "description",
            required: false,
            default: '',
            length: 16777215,
            db: (prop) => dbMediumText(prop),
            zod: (prop) => zodMediumText(prop),
            view: [],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'cronJobId',
            required: false,
            filterQualifier: false,
            default: undefined,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'cronjob',
                kind: 'CronJob',
            },
            view: ['owner',],
            edit: ['owner'],
        },
    ],
};