import { baseSchemaProps, dbString, zodString, dbInt, dbEnum, dbRelation } from '../helpers.mjs';

export const maintenanceTaskSchema = {
    kind: 'MaintenanceTask',
    tableName: 'maintenancetasks',
    owner: ['admin', 'maintenanceManager'],
    props: [
        ...baseSchemaProps,
        {
            type: "string",
            name: "task",
            required: true,
            unique: false,
            length: 128,
            default: '',
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop),
            view: ['owner', 'productionManager'],
            edit: ['owner'],
        },
        {
            type: "enum",
            name: "recurrence",
            required: true,
            length: 20,
            default: 'monthly',
            db: (prop) => dbEnum(prop),
            enums: ['yearly', 'monthly', 'weekly', 'daily'],
            enumLabels: ['Yearly', 'Monthly', 'Weekly', 'Daily'],
            view: ['owner',],
            edit: ['owner'],
        },
        {
            type: "enum",
            name: "disabled",
            required: true,
            default: 'active',
            db: (prop) => dbEnum(prop),
            enums: ['disabled', 'active'],
            enumLabels: ['Disabled', 'Active'],
            view: ['owner', 'productionManager'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'shopEquipmentId',
            required: true,
            db: (prop) => dbRelation(prop),
            view: ['owner', 'productionManager'],
            edit: ['owner'],
            relation: {
                type: 'parent',
                name: 'shopEquipment',
                kind: 'ShopEquipment',
            },
        },
        {
            type: "integer",
            name: 'months',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(12),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'weeks',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(5),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'days',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(31),
            view: ['owner'],
            edit: ['owner'],
        },
    ],
};