import { TopicRule } from '@pulumi/aws/iot';
import { baseSchemaProps, dbString, zodString, dbEnum, dbBoolean, dbRelation } from '../helpers.mjs';

export const maintenanceTaskSchema = {
    kind: 'MaintenanceTask',
    tableName: 'maintenanceTasks',
    owner: ['$id', 'admin'],
    props: [
        ...baseSchemaProps,
        {
            type: "string",
            name: "task",
            required: true,
            unique: false,
            length: 128,
            default: '',
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "enum",
            name: "recurrence",
            required: true,
            length: 20,
            default: 'monthly',
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop),
            enums: ['yearly', 'monthly', 'weekly', 'daily'],
            enumLabels: ['Yearly', 'Monthly', 'Weekly', 'Daily'],
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "boolean",
            name: "disabled",
            required: true,
            default: false,
            default: '',
            db: (prop) => dbBoolean(prop),
            enums: [false, true],
            enumLabels: ['Disabled', 'Active'],
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'shopEquipmentId',
            required: true,
            db: (prop) => dbRelation(prop),
            view: ['owner'],
            edit: ['owner'],
            relation: {
                type: 'parent',
                name: 'shopEquipment',
                kind: 'ShopEquipment',
            },
        },
        {
            type: "integer",
            name: 'months',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'weeks',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'days',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop),
            view: ['owner'],
            edit: ['owner'],
        },
    ],
};