import { baseSchemaProps, dbString, zodString, dbEnum, dbBoolean, dbText, zodText, dbRelation, dbDateTime, dbTimestamp, dbInt, dbJson, zodNumber, zodJsonObject } from '../helpers.mjs';

export const maintenancescheduleSchema = {
    kind: 'MaintenanceSchedule',
    tableName: 'maintenanceschedules',
    owner: ['admin', 'maintenanceManager'],
    props: [
        ...baseSchemaProps,
        {
            type: "enum",
            name: "recurrence",
            required: true,
            length: 20,
            default: 'monthly',
            db: (prop) => dbEnum(prop),
            enums: ['yearly', 'monthly', 'weekly', 'daily'],
            enumLabels: ['Yearly', 'Monthly', 'Weekly', 'Daily'],
            view: ['owner',],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'months',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(12),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'weeks',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(5),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "integer",
            name: 'days',
            required: false,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).gte(0).lte(31),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'maintenanceItemSetId',
            required: true,
            length: 36,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'maintenanceItemSet',
                kind: 'MaintenanceItemSet',
            },
            default: undefined,
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'maintenanceTaskId',
            required: true,
            length: 36,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'maintenanceTask',
                kind: 'MaintenanceTask',
            },
            default: undefined,
            view: ['owner'],
            edit: ['owner'],
        },
    ],
};