import { baseSchemaProps, dbString, zodString, zodMediumText, dbEnum, dbBoolean, dbMediumText, zodText, dbRelation, dbDateTime, dbTimestamp, dbInt, dbJson, zodNumber, zodJsonObject } from '../helpers.mjs';

export const maintenanceTicketSchema = {
    kind: 'MaintenanceTicket',
    tableName: 'maintenancetickets',
    owner: ['admin', 'maintenanceManager', 'productionManager'],
    props: [
        ...baseSchemaProps,
        {
            type: "string",
            name: "name",
            required: true,
            filterQuery: true,
            length: 60,
            default: '',
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop),
            view: [],
            edit: ['owner'],
        },
        {
            type: "int",
            name: "ticketNumber",
            filterQualifier: true,
            required: false,
            default: 0,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop),
            view: ['public'],
            edit: [],
        },
        {
            type: "string",
            name: "description",
            required: true,
            length: 60,
            default: '',
            db: (prop) => dbMediumText(prop),
            zod: (prop) => zodMediumText(prop),
            view: [],
            edit: ['owner'],
        },
        {
            type: "enum",
            name: 'type',
            required: true,
            filterQualifier: true,
            length: 20,
            default: 'routine',
            db: (prop) => dbEnum(prop),
            enums: ['routine', 'needs_help'],
            enumLabels: ['Routine', 'Needs Help'],
            view: [],
            edit: ['owner'],
        },
        {
            type: "enum",
            name: 'severity',
            required: true,
            filterQualifier: true,
            length: 20,
            default: 'working',
            db: (prop) => dbEnum(prop),
            enums: ['working', 'intermittent', 'down'],
            enumLabels: ['Working', 'Intermittent', 'Down'],
            view: [],
            edit: ['owner'],
        },
        {
            type: "enum",
            name: 'status',
            required: true,
            filterQualifier: true,
            length: 20,
            default: 'resolved',
            db: (prop) => dbEnum(prop),
            enums: ['resolved', 'unresolved'],
            enumLabels: ['Resolved', 'Unresolved'],
            view: [],
            edit: ['owner'],
        },
        {
            type: "int",
            name: "resolutionMinutes",
            required: false,
            default: 0,
            db: (prop) => dbInt(prop),
            zod: (prop) => zodNumber(prop).positive(),
            view: ['public'],
            edit: [],
        },
        {
            type: "string",
            name: "submittedBy",
            required: true,
            filterQualifier: true,
            default: '',
            length: 64,
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop),
            view: ['public'],
            edit: ['owner'],
        },

        // 1:N relationship - aka a relationship to my children
        {
            type: "virtual",
            name: 'maintenanceTicketId', // the name of this record's id in the remote table
            required: false,
            view: ['public'],
            edit: [],
            relation: {
                type: 'child',
                name: 'remarks',
                kind: 'MaintenanceRemark',
            },
        },
        {
            type: "virtual",
            name: 'maintenanceTicketId', // the name of this record's id in the remote table
            required: false,
            view: ['public'],
            edit: [],
            relation: {
                type: 'child',
                name: 'files',
                kind: 'MaintenanceFile',
            },
        },
        {
            type: "id",
            name: 'maintenanceTaskId', // the name of the remote record's id in this table
            required: true,
            filterQualifier: true,
            length: 36,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'task',
                kind: 'MaintenanceTask',
            },
            default: undefined,
            view: ['public'],
            edit: ['owner'],
        },
        {
            type: "id",
            name: 'maintenanceItemId', // the name of the remote record's id in this table
            required: true,
            filterQualifier: true,
            length: 36,
            db: (prop) => dbRelation(prop),
            relation: {
                type: 'parent',
                name: 'item',
                kind: 'MaintenanceItem',
            },
            default: undefined,
            view: ['public'],
            edit: ['owner'],
        },
    ],
};