import { baseSchemaProps, dbString, zodString, dbEnum, dbBoolean, dbRelation } from '../helpers.mjs';

export const shopEquipmentSchema = {
    kind: 'ShopEquipment',
    tableName: 'shopEquipment',
    owner: ['$id', 'admin'],
    props: [
        ...baseSchemaProps,
        {
            type: "string",
            name: "name",
            required: true,
            filterQuery: true,
            unique: true,
            length: 60,
            default: '',
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "string",
            name: "manufacturer",
            required: true,
            filterQuery: true,
            unique: true,
            length: 256,
            default: '',
            db: (prop) => dbString(prop),
            zod: (prop) => zodString(prop).email(),
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "boolean",
            name: "obsolete",
            required: true,
            default: false,
            filterQuery: true,
            length: 60,
            default: '',
            db: (prop) => dbBoolean(prop),
            enums: [false, true],
            enumLabels: ['In use', 'Obsolete'],
            view: ['owner'],
            edit: ['owner'],
        },
        {
            type: "virtual",
            name: 'shopEquipmentId',
            required: false,
            view: ['public'],
            edit: [],
            relation: {
                type: 'child',
                name: 'tasks',
                kind: 'MaintenanceTasks',
            },
        },
    ],
};